service:
   frontend:
      build:
         context: ./backend
         image: sahil9079/backend
         port:
            - "80:80"
         depends_on:
            - backend
   backend:
      build:
         context: ./frontend
         image: sahil9079/frontend
         port:
            - "5000:5000"
